### ISSUE TITLE
INSTALL ON WINDOWS

### ISSUE THREAD

**Issue by x-has** [Idontwan/SISG4HEI_Alpha#1]
I HAVE THIS ERR
C:\Windows\system32>python E:\SISG4HEI_Alpha-main\GUI\GUI_Base.py
Traceback (most recent call last):
  File "E:\SISG4HEI_Alpha-main\GUI\GUI_Base.py", line 11, in <module>
    import GUI_Semantic as GS
  File "E:\SISG4HEI_Alpha-main\GUI\GUI_Semantic.py", line 14, in <module>
    import GUI_Layout as GL
  File "E:\SISG4HEI_Alpha-main\GUI\GUI_Layout.py", line 17, in <module>
    import GUI_ActivitySchedule as GAS
  File "E:\SISG4HEI_Alpha-main\GUI\GUI_ActivitySchedule.py", line 18, in <module>
    import GUI_TravelPattern as GT
  File "E:\SISG4HEI_Alpha-main\GUI\GUI_TravelPattern.py", line 14, in <module>
    import GUI_Interface as GI
  File "E:\SISG4HEI_Alpha-main\GUI\GUI_Interface.py", line 20, in <module>
    import Tools_ as Tl
ModuleNotFoundError: No module named 'Tools_'

**Comment by Idontwan** [comment]
Now, the Windows version is uploaded to branch "windows"

**Comment by x-has** [comment]
Thanks, 
what I have to do now :  delete the old one !
